# Generated by Django 4.2.3 on 2023-07-30 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_book_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="book.book"
            ),
        ),
    ]
