# Generated by Django 4.2.3 on 2023-07-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_section_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="section_description",
            field=models.CharField(default="", max_length=500),
        ),
    ]
