# Generated by Django 4.2.3 on 2023-08-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_section_book_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="sub_sections",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
